name: check if formula urls alive

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]
  schedule:
    - cron: '0 22 * * *'

jobs:
  check:

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - uses: actions/checkout@v4

      - run: install -d ~/.ndk-pkg/repos.d/official-core

      - run: mv formula ~/.ndk-pkg/repos.d/official-core/

      - run: |
            cat > ~/.ndk-pkg/repos.d/official-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-official-core
            branch: master
            pinned: 1
            enabled: 1
            timestamp-created: 1673675503
            timestamp-updated: 1676399969
            EOF

      - run: ndk-pkg env
      - run: ndk-pkg setup
      - run: ndk-pkg sysinfo
      - run: |
          for item in $(ndk-pkg ls-available)
          do
            ndk-pkg fetch "$item"
          done
