name: check if formula urls alive

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]
  schedule:
    - cron: '0 22 * * *'

jobs:
  check:

    runs-on: ubuntu-latest

    container: ubuntu:24.04

    steps:
      - uses: actions/checkout@v4

      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo

      - run: ./ndk-pkg formula-repo-add official-core https://github.com/leleliu008/ndk-pkg-formula-repository-official-core
      - run: mv formula ~/.ndk-pkg/repos.d/official-core/

      - run: |
          for item in $(./ndk-pkg ls-available)
          do
              ./ndk-pkg fetch "$item"
          done
