name: workflow17

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  ubuntu:
    #if: false

    strategy:

      fail-fast: false

      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        opt: ['--static', '']
        pkg: [pybind11,q,qpdf,qrencode,quickjs,ragel,rancher,rang,rapidjson,rav1e,rclone,re2c,restic,resvg,rhash,ripgrep,ripgrep-all,rlwrap,robin-map,rover,rsass,rsync,rtmpdump,rtorrent,ruff,rust-analyzer,ruy,samurai,sassc,scc]

    runs-on: ubuntu-latest

    container: ubuntu:24.04

    steps:
      - uses: actions/checkout@v4

      - run: apt -y update
      - run: apt -y install curl

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}

  alpine:
    #if: false

    strategy:

      fail-fast: false

      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        opt: ['--static', '']
        pkg: [pybind11,q,qpdf,qrencode,quickjs,ragel,rancher,rang,rapidjson,rav1e,rclone,re2c,restic,resvg,rhash,ripgrep,ripgrep-all,rlwrap,robin-map,rover,rsass,rsync,rtmpdump,rtorrent,ruff,rust-analyzer,ruy,samurai,sassc,scc]

    runs-on: ubuntu-latest

    container: alpine

    steps:
      - uses: actions/checkout@v4

      - run: wget https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod +x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}

  macos:
    #if: false

    strategy:

      fail-fast: false

      matrix:
        os:  [macos-14]
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        opt: ['--static', '']
        pkg: [pybind11,q,qpdf,qrencode,quickjs,ragel,rancher,rang,rapidjson,rav1e,rclone,re2c,restic,resvg,rhash,ripgrep,ripgrep-all,rlwrap,robin-map,rover,rsass,rsync,rtmpdump,rtorrent,ruff,rust-analyzer,ruy,samurai,sassc,scc]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg about
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg formula-repo-add my_repo https://github.com/leleliu008/ndk-pkg-formula-repository-my_repo
      - run: mv formula ~/.ndk-pkg/repos.d/my_repo/
      - run: ./ndk-pkg-install ${{ matrix.pkg }} ${{ matrix.abi }} ${{ matrix.opt }}
