name: workflow7

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  container:

    strategy:

      fail-fast: false

      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        pkg: [pdfium,pget,physfs,pigz,pjsip,pkgconf,pkg-config,plog,pngquant,poco,ppkg,procs,progress,proj,proot2,protobuf,psimd,pup,putty,pybind11,qpdf,qrencode,quiche,quickjs,rang,rapidjson,rclone,re2c,restic,ripgrep,rlwrap,rsass,rsync,rtmpdump,rtorrent,ruff,rust-analyzer,sassc,scc,sd,shc,shell2http,shiori,silicon,sjpeg,sl,soundtouch,spdlog,sqlite3,starship]

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - run: export -p

      - uses: actions/checkout@v4

      - if:  ${{ github.ref_name == 'dev' }}
        run: |
            curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/dev/ndk-pkg
            chmod +x ndk-pkg
            mv ndk-pkg /usr/bin/ndk-pkg

      - run: /usr/bin/ndk-pkg env
      - run: /usr/bin/ndk-pkg setup
      - run: /usr/bin/ndk-pkg sysinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core

      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            created: 1673675503
            updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: |
          MIN_SDK_API_LEVEL=$(/usr/bin/ndk-pkg info-available ${{ matrix.pkg }} api-min)
          if [ -z "$MIN_SDK_API_LEVEL" ] ; then
            MIN_SDK_API_LEVEL=21
          fi
          /usr/bin/ndk-pkg install android-$MIN_SDK_API_LEVEL-${{ matrix.abi }}/${{ matrix.pkg }}


  macos:
    if: false
    strategy:

      fail-fast: false

      matrix:
        os:  [macos-12, macos-13]
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]
        pkg: [pdfium,pget,physfs,pigz,pjsip,pkgconf,pkg-config,plog,pngquant,poco,ppkg,procs,progress,proj,proot2,protobuf,psimd,pup,putty,pybind11,qpdf,qrencode,quiche,quickjs,rang,rapidjson,rclone,re2c,restic,ripgrep,rlwrap,rsass,rsync,rtmpdump,rtorrent,ruff,rust-analyzer,sassc,scc,sd,shc,shell2http,shiori,silicon,sjpeg,sl,soundtouch,spdlog,sqlite3,starship]

    runs-on: ${{ matrix.os }}

    steps:
      - run: export -p

      - uses: actions/checkout@v4

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg env
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg ndkinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core
      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            created: 1673675503
            updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: |
          MIN_SDK_API_LEVEL=$(./ndk-pkg info-available ${{ matrix.pkg }} api-min)
          if [ -z "$MIN_SDK_API_LEVEL" ] ; then
            MIN_SDK_API_LEVEL=21
          fi
          ./ndk-pkg install android-$MIN_SDK_API_LEVEL-${{ matrix.abi }}/${{ matrix.pkg }}
