name: workflow9

on:
  push:
    branches: [ master,dev ]
  pull_request:
    branches: [ master,dev ]

jobs:
  container:

    strategy:

      fail-fast: false

      matrix:
        arch: [armv7a, aarch64, i686, x86_64]
        pkg: [xmake,xorriso,xpup,xxd,xz,yaml-cpp,yasm,youtubedr,yq,yyjson,zeromq,zip,zlib-ng,zlog,zola,zoxide,zsh,zstd,zsync]

    runs-on: ubuntu-latest

    container: fpliu/ndk-pkg

    steps:
      - run: export -p

      - uses: actions/checkout@v3

      - if:  ${{ github.ref_name == 'dev' }}
        run: |
            curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/dev/ndk-pkg
            chmod +x ndk-pkg
            mv ndk-pkg /usr/bin/ndk-pkg

      - run: /usr/bin/ndk-pkg env
      - run: /usr/bin/ndk-pkg setup
      - run: /usr/bin/ndk-pkg sysinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core

      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            created: 1673675503
            updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: |
          MIN_SDK_API_LEVEL=$(/usr/bin/ndk-pkg info-available ${{ matrix.pkg }} api-min)
          if [ -z "$MIN_SDK_API_LEVEL" ] ; then
            MIN_SDK_API_LEVEL=21
          fi
          /usr/bin/ndk-pkg install android-$MIN_SDK_API_LEVEL-${{ matrix.arch }}/${{ matrix.pkg }}


  macos:
    if: false
    strategy:

      fail-fast: false

      matrix:
        os:  [macos-12, macos-13]
        arch: [armv7a, aarch64, i686, x86_64]
        pkg: [xmake,xorriso,xpup,xxd,xz,yaml-cpp,yasm,youtubedr,yq,yyjson,zeromq,zip,zlib-ng,zlog,zola,zoxide,zsh,zstd,zsync]

    runs-on: ${{ matrix.os }}

    steps:
      - run: export -p

      - uses: actions/checkout@v3

      - run: curl -LO https://raw.githubusercontent.com/leleliu008/ndk-pkg/${{ github.ref_name }}/ndk-pkg
      - run: chmod u+x ndk-pkg

      - run: ./ndk-pkg env
      - run: ./ndk-pkg setup
      - run: ./ndk-pkg sysinfo
      - run: ./ndk-pkg ndkinfo

      - run: install -d ~/.ndk-pkg/repos.d/offical-core
      - run: |
            cat > ~/.ndk-pkg/repos.d/offical-core/.ndk-pkg-formula-repo.yml <<EOF
            url: https://github.com/leleliu008/ppkg-formula-repository-offical-core
            branch: master
            pinned: 1
            enabled: 1
            created: 1673675503
            updated: 1676399969
            EOF

      - run: mv formula ~/.ndk-pkg/repos.d/offical-core/

      - run: |
          MIN_SDK_API_LEVEL=$(./ndk-pkg info-available ${{ matrix.pkg }} api-min)
          if [ -z "$MIN_SDK_API_LEVEL" ] ; then
            MIN_SDK_API_LEVEL=21
          fi
          ./ndk-pkg install android-$MIN_SDK_API_LEVEL-${{ matrix.arch }}/${{ matrix.pkg }}
