name: compare-versions

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]
  schedule:
    - cron: '0 20 * * *'

jobs:
  schedule:

    runs-on: macos-14

    steps:
      - run: brew update

      - uses: actions/checkout@v4

      - run: ./compare-versions-with-brew
      - run: ./compare-versions-with-maven
